name: Testing when someone push
on:
  push:
    branches: ['khoe']
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: npm ci
      - name: Run tests
        run: npm run test
